-- Conéctate primero a la base:
-- \c electionsdb

BEGIN;

------------------------------------------------------------
-- 1. Tipos y extensiones opcionales
------------------------------------------------------------

-- (Opcional, sólo si algún día quieres usar PostGIS)
-- CREATE EXTENSION IF NOT EXISTS postgis;

-- Tipo ENUM para los tipos de territorio
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'territorio_tipo') THEN
    CREATE TYPE territorio_tipo AS ENUM (
      'ccaa',
      'provincia',
      'municipio',
      'distrito',
      'seccion',
      'circunscripcion',
      'cera'
    );
  END IF;
END$$;

------------------------------------------------------------
-- 2. Tabla de tipos de elección
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tipos_eleccion (
  codigo        VARCHAR(1)   PRIMARY KEY,       -- 'G', 'A', 'M', 'E', etc.
  descripcion   VARCHAR(100) NOT NULL
);

------------------------------------------------------------
-- 3. Tabla de elecciones
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS elecciones (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_eleccion  VARCHAR(1) NOT NULL,
  year           CHAR(4)    NOT NULL,
  mes            CHAR(2)    NOT NULL,
  dia            CHAR(2)    NOT NULL,
  fecha          DATE       NULL,
  codigo_ccaa    CHAR(2)    NULL,
  numero_vuelta  SMALLINT   DEFAULT 1,
  descripcion    VARCHAR(255) NULL,
  ambito         VARCHAR(50)  NULL,         -- "nacional", "autonómico", "municipal"...
  slug           VARCHAR(50)  NULL,

  CONSTRAINT fk_elecciones_tipo
    FOREIGN KEY (tipo_eleccion)
    REFERENCES tipos_eleccion (codigo),

  CONSTRAINT uq_eleccion_tipo_fecha
    UNIQUE (tipo_eleccion, year, mes, codigo_ccaa, numero_vuelta)
);

------------------------------------------------------------
-- 4. Tabla de territorios
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS territorios (
  id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo                  territorio_tipo NOT NULL,
  codigo_ccaa           CHAR(2)   NULL,
  codigo_provincia      CHAR(2)   NULL,
  codigo_municipio      CHAR(3)   NULL,
  codigo_distrito       CHAR(2)   NULL,
  codigo_seccion        CHAR(4)   NULL,
  codigo_circunscripcion CHAR(3)  NULL,
  nombre                VARCHAR(255) NULL,
  codigo_completo       VARCHAR(13)  NULL,
  parent_id             INT  NULL,

  CONSTRAINT fk_territorios_parent
    FOREIGN KEY (parent_id) REFERENCES territorios(id),

  CONSTRAINT uq_territorio_codigos
    UNIQUE (
      tipo,
      codigo_ccaa,
      codigo_provincia,
      codigo_municipio,
      codigo_distrito,
      codigo_seccion,
      codigo_circunscripcion
    )
);

CREATE INDEX IF NOT EXISTS idx_territorios_parent
  ON territorios(parent_id);

------------------------------------------------------------
-- 5. Tabla de partidos_recodes
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS partidos_recode (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partido_recode   VARCHAR(50)  NOT NULL,
  agrupacion       VARCHAR(50)  NULL,
  color            VARCHAR(7)   NULL,

  CONSTRAINT uq_partidos_recode
    UNIQUE (partido_recode)
);

CREATE INDEX IF NOT EXISTS idx_partidos_recode
  ON partidos_recode(partido_recode);

------------------------------------------------------------
-- 6. Tabla de partidos
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS partidos (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partido_recode_id    INT NULL,
  siglas               VARCHAR(255)  NULL,
  denominacion         VARCHAR(255) NULL,

  CONSTRAINT fk_partidos_recode
    FOREIGN KEY (partido_recode_id) REFERENCES partidos_recode(id),

  CONSTRAINT uq_partidos
    UNIQUE (siglas, denominacion)
);

CREATE INDEX IF NOT EXISTS idx_partidos_siglas
  ON partidos(siglas);

CREATE INDEX IF NOT EXISTS idx_partidos_recode_id
  ON partidos(partido_recode_id);

------------------------------------------------------------
-- 7. Resumen territorial (censo, participación, etc.)
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS resumen_territorial (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eleccion_id      INT NOT NULL,
  territorio_id    INT NOT NULL,
  censo_ine        INT NULL,
  participacion_1  INT NULL,
  participacion_2  INT NULL,
  participacion_3  INT NULL,
  votos_validos    INT NULL,
  abstenciones     INT NULL,
  votos_blancos    INT NULL,
  votos_nulos      INT NULL,
  nrepresentantes  INT NULL,

  CONSTRAINT fk_resumen_eleccion
    FOREIGN KEY (eleccion_id) REFERENCES elecciones(id),

  CONSTRAINT fk_resumen_territorio
    FOREIGN KEY (territorio_id) REFERENCES territorios(id),

  CONSTRAINT uq_resumen_eleccion_territorio
    UNIQUE (eleccion_id, territorio_id)
);

CREATE INDEX IF NOT EXISTS idx_resumen_territorio
  ON resumen_territorial(territorio_id);

------------------------------------------------------------
-- 8. Votos territoriales (por partido, por territorio)
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS votos_territoriales (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eleccion_id    INT NOT NULL,
  territorio_id  INT NOT NULL,
  partido_id     INT NOT NULL,
  votos          INT NULL,
  representantes INT NULL,

  CONSTRAINT fk_votos_eleccion
    FOREIGN KEY (eleccion_id) REFERENCES elecciones(id),

  CONSTRAINT fk_votos_territorio
    FOREIGN KEY (territorio_id) REFERENCES territorios(id),

  CONSTRAINT fk_votos_partido
    FOREIGN KEY (partido_id) REFERENCES partidos(id),

  CONSTRAINT uq_votos_eleccion_territorio_partido
    UNIQUE (eleccion_id, territorio_id, partido_id)
);

CREATE INDEX IF NOT EXISTS idx_votos_eleccion_territorio
  ON votos_territoriales(eleccion_id, territorio_id);

CREATE INDEX IF NOT EXISTS idx_votos_partido
  ON votos_territoriales(partido_id);

------------------------------------------------------------
-- 9. Resumen CERA
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS resumen_cera (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eleccion_id      INT NOT NULL,
  territorio_id    INT NOT NULL,    -- circunscripción/provincia CERA
  censo_ine        INT NULL,
  votos_validos    INT NULL,
  abstenciones     INT NULL,
  votos_blancos    INT NULL,
  votos_nulos      INT NULL,

  CONSTRAINT fk_resumen_cera_eleccion
    FOREIGN KEY (eleccion_id) REFERENCES elecciones(id),

  CONSTRAINT fk_resumen_cera_territorio
    FOREIGN KEY (territorio_id) REFERENCES territorios(id),

  CONSTRAINT uq_resumen_cera_eleccion_territorio
    UNIQUE (eleccion_id, territorio_id)
);

------------------------------------------------------------
-- 10. Votos CERA
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS votos_cera (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eleccion_id   INT NOT NULL,
  territorio_id INT NOT NULL,
  partido_id    INT NOT NULL,
  votos         INT NULL,

  CONSTRAINT fk_votos_cera_eleccion
    FOREIGN KEY (eleccion_id) REFERENCES elecciones(id),

  CONSTRAINT fk_votos_cera_territorio
    FOREIGN KEY (territorio_id) REFERENCES territorios(id),

  CONSTRAINT fk_votos_cera_partido
    FOREIGN KEY (partido_id) REFERENCES partidos(id),

  CONSTRAINT uq_votos_cera_eleccion_territorio_partido
    UNIQUE (eleccion_id, territorio_id, partido_id)
);

CREATE INDEX IF NOT EXISTS idx_votos_cera_eleccion_territorio
  ON votos_cera(eleccion_id, territorio_id);

COMMIT;

